---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: docker-services
spec:
  type: ClusterIP
  ports:
  - port: 6767
    targetPort: 6767
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bazarr
  namespace: docker-services
subsets:
- addresses:
  - ip: 192.168.1.40
  ports:
  - port: 6767
---
