---

include:
  - compose/arr.yaml
  - compose/iot.yaml
  - compose/base.yaml
  - compose/proxy.yaml
  - compose/media.yaml
  - compose/downloads.yaml
  - compose/automation.yaml
  - compose/monitoring.yaml
  - compose/system.yaml
  - compose/ai.yaml
  - compose/gitops.yaml
  - compose/database.yaml
