apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls
  namespace: adguard
spec:
  secretName: adguard-tls-secret # K8s will save the cert here
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dns.erwanleboucher.dev
  dnsNames:
  - dns.erwanleboucher.dev
