---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-dashboard
  namespace: adguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dns.erwanleboucher.dev
      secretName: adguard-tls
  rules:
    - host: dns.erwanleboucher.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-ha-web
                port:
                  number: 3000
