---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:6DX3kak=,iv:C30Jv362i1ZKy8wFJ0ozskqLmVE63qau6qnWFfuK5pc=,tag:pLCfur6/kOpZhQFOVMPyvQ==,type:str]
  admin-password: ENC[AES256_GCM,data:wX+pLanI7F1+vuAwD3C26f+iLi0=,iv:NoIGbspQU8xj130wX9pwkgAa/AM9Puxb/8LOB4JIhVw=,tag:t4DlX8zNjOP6USpvfBkA/g==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b3ZBd1l0NzUwQ1BaRVBL
        YzlBcmZyV1gyeExzR0c0d3R4bzFramJESHhjCmViaXdWdzkza1phbkxmcHNncEhY
        eWZjZm4rNTd4NlhKVmU1OGJKMDVGdEUKLS0tIFZ0UkZIZ3JjajltMUxBOXNkQk9z
        Nk9BYnZOeTVyYlJOOEVSb0N6QkFzYlUKbKurNW73wg/KVIS5vYNkWv+eN2rHm0cL
        uYBUipNPecYs36cVpEm/fo39LSHQ35oloFTb372ggJ7JICLVv5PUvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T10:52:12Z"
  mac: ENC[AES256_GCM,data:agKMIqGaeD+ZyHdxWb9jiChwl4y2N8I3/8KxWX6QKjLYI47Vcqnq5hmAjmXBYdcHUHtLH+81LdEYf5rFEy53focaJavMXmZkJOx6C+WNAaePKqWzW2M4kLGuTx1NZrLvieqbJr/hOxJosQSBbcbgVtAWNmh3mGKPWY72+miCx5A=,iv:Ay1iKP+gg+ipOdRxIaSZ+p1zh7ht/2Y8Tp3ujvUGtSw=,tag:h+yAXb2C7gumx0IAKDQRjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
