---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  # TODO: Split these from docker-services.yaml and external-services.yaml
  # - autobrr
  # - profilarr
  # - n8n
  # - wizarr
  # - homepage
