---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  # - certificate.yaml  # Removed: cert-manager annotation creates this automatically
  - helmrelease.yaml
