---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: docker-services
spec:
  type: ClusterIP
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
  namespace: docker-services
subsets:
- addresses:
  - ip: 192.168.1.40
  ports:
  - port: 7878
---
