image:
  repository: louislam/uptime-kuma
  tag: "2.0.2"
  pullPolicy: Always


nodeSelector:
  kubernetes.io/hostname: "k3s"



service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.56 # The VIP we defined earlier
  port: 80
  targetPort: 3001
  # Force traffic to stay local to the Freebox
  externalTrafficPolicy: Local
  annotations:
    metallb.universe.tf/allow-shared-ip: "uptime-vip"


# Mariadb configurations
mariadb:
  enabled: true


resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi
