---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin
  # TODO: Split these from docker-services.yaml
  # - sonarr
  # - radarr
  # - prowlarr
  # - bazarr
  # - jellyseerr
