apiVersion: v1
kind: Service
metadata:
  name: adguard-primary-admin
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-vip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.54
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/instance: adguard-primary
  ports:
    - name: http-admin-primary
      port: 3000
      targetPort: 80  # The container's internal web port
      protocol: TCP
