apiVersion: v1
kind: Service
metadata:
  name: adguard-vip
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-vip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.53
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP

    - name: https-doh
      port: 443
      targetPort: 443
      protocol: TCP

    # NEW: DNS-over-TLS (DoT)
    - name: tls-dot
      port: 853
      targetPort: 853
      protocol: TCP
