---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: docker-services
spec:
  type: ClusterIP
  ports:
  - port: 9696
    targetPort: 9696
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prowlarr
  namespace: docker-services
subsets:
- addresses:
  - ip: 192.168.1.40
  ports:
  - port: 9696
---
