settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  stalled_tag: stalledDL
  private_tag:
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  rem_unregistered_filter_completed: false
  cat_update_all: true
  force_auto_tmm_ignore_tags: []
  disable_qbt_default_share_limits: true
  tag_stalled_torrents: true
  rem_unregistered_ignore_list: []
  rem_unregistered_grace_minutes: 10
  rem_unregistered_max_torrents: 10
qbt:
  host: http://gluetun:8081
  user: !ENV QBIT_USER
  pass: !ENV QBIT_PASS

directory:
  root_dir: /data/downloads/torrents

  recycle_bin: /data/downloads/torrents/.RecycleBin
  torrents_dir:
cat:
  radarr: /data/downloads/torrents
  tv-sonarr: /data/downloads/torrents

tracker:
  leech:
    tag: TorrentLeech
  tracker.opentrackr.org:
    tag: tracker.opentrackr.org
nohardlinks:
  radarr:
  tv-sonarr:

share_limits:
  noHL:
    priority: 1
    include_all_tags:
    - noHL
    max_ratio: 1.0
    max_seeding_time: 8d
    min_last_active: 30m
    cleanup: true

    add_group_to_tag: false
recyclebin:
  enabled: true
  empty_after_x_days: 7
  save_torrents: false
  split_by_category: false
webhooks:
  error:
  run_start:
  run_end:
  function:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
orphaned:
  empty_after_x_days:
  exclude_patterns:
  max_orphaned_files_to_delete: 50
  min_file_age_minutes: 0
